/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Upgrade": "升级",
    "Upgrades": "升级",
    "Until gate opens": "直到大门打开",
    "When turned off may reduce CPU usage (requires reload when turned on": "关闭时可能会降低 CPU 使用率（开启时需要重新加载",
    "Wow message such entertain": "哇消息这样的娱乐",
    "yes": "是",
    "Click anywhere to start": "单击任意位置开始",
    "Click it to get crystals": "点击获取水晶",
    "Click it when you will have a key to open it or when time reaches 00:00:00 click to enter it": "有钥匙打开或时间到00:00:00时点击进入",
    "Clock Room Original Soundtrack": "时钟室原声带",
    "close": "关闭",
    "Credits": "学分",
    "Crush Shards": "粉碎碎片",
    "Crushing shards gives you 100 dust": "粉碎碎片给你 100 灰尘",
    "Delete": "删除",
    "delete mods": "删除模组",
    "Deposit Prestige": "存款威望",
    "Do you really want to Rewind Time?": "你真的想倒带时间吗？",
    "Do you want to enter the gate?": "你想进大门吗？",
    "Drink": "喝",
    "Dust": "灰尘",
    "element.": "元素。",
    "Flask capacity": "烧瓶容量",
    "Flask is not ready": "烧瓶没有准备好",
    "Flask upgrades": "烧瓶升级",
    "Gain more fillage to flask": "获得更多的烧瓶填充物",
    "Game Saved": "游戏已保存",
    "Gate - 500 prestige points": "大门 - 500 威望点",
    "Get 10% of seconds you had before rewinding time": "获得倒带时间前 10% 的秒数",
    "Get it": "得到它",
    "Go back": "回去",
    "Increase capacity of flask": "增加烧瓶容量",
    "Info": "信息",
    "Keep in mind that game is saved every 30 seconds": "请记住，游戏每 30 秒保存一次",
    "Less time consuming Tick Tocks": "更省时的 嘀嗒",
    "Load": "加载",
    "load new": "加载新",
    "Loaded mod": "加载模组",
    "Loading crucial game files...": "正在加载重要的游戏文件...",
    "Main website": "主要网站",
    "Mod configurations automatically load and save": "Mod配置自动加载和保存",
    "Mod settings": "模组设置",
    "Mods (guide": "模组（指南",
    "Music": "音乐",
    "no": "不",
    "on": "在",
    "Other things": "其他事情",
    "Past money": "过去的钱",
    "Pick your desired upgrades and go back in time for more prestige": "选择您想要的升级并及时返回以获得更多声望",
    "Pouek_": "普克_",
    "Pure magic": "纯粹的魔法",
    "Reloading...": "正在重新加载...",
    "Report a bug": "报告错误",
    "Rewind Time": "倒带时间",
    "Rewinding Time...": "时光倒流...",
    "Sacrifice": "牺牲",
    "save mods": "保存模组",
    "Set of things you can do with your save": "你可以用你的存档做的事情",
    "Settings &": "设置 &",
    "Shards": "碎片",
    "Shop": "店铺",
    "Smelt Dust": "冶炼尘埃",
    "Smelting dust gives you 0.1% of required mass for key": "冶炼粉尘为您提供钥匙所需质量的 0.1%",
    "SoundCloud": "声云",
    "Studio website": "工作室网站",
    "Time left until next Tick Tock": "距离下一个 嘀嗒 还有时间",
    "Time Shard - 1000 prestige points": "时间碎片 - 1000 声望点",
    "Time Travel - 100 prestige points": "时间旅行 - 100 声望点数",
    "Background effect": "背景效果",
    "Please wait...": "请稍候...",
    "Sacrificial Multiplier": "牺牲乘数",
    "You'll get a reward...": "你会得到奖励...",
    "Your browser does not support the": "您的浏览器不支持",
    "You escaped!": "你逃走了！",
    "Upgrade multiplier": "升级乘数",
    "BUY": "购买",
    "Measuring internet speed...": "测量网速...",
    "audio": "音频",
    "But where did you end up?": "但你最终在哪里？",
    "By deafult turned on to feel the ambient": "默认开启以感受环境",
    "\"Gate to a portal to somewhere...\"": "\"通往某处的传送门的大门......\"",
    "\"Get 10% of your seconds that you had before rewinding time\"": "\"获得倒带时间前 10% 的秒数\"",
    "\"New things\"": "\“新事物\”",
    "\"Sacrifice some multiplier for huge amount of seconds\"": "\"在大量秒数中牺牲一些乘数\"",
    "\"You can see your whole life in it\"": "\"你可以在里面看到你的整个人生\"",
    "\"Your pass to those sweet upgrades\"": "\"你的甜蜜升级通行证\"",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Upgrade \n": "升级 \n",
    "You don't have this upgrade yet": "您还没有此升级",
    "Required percent of fill: ": "所需填充百分比：",
    "Sacrifice \n": "牺牲 \n",
    "Ticket - ": "门票 - ",
    "Shop - ": "商店 - ",
    "Flask capacity is: ": "烧瓶容量为：",
    "LV.": "等级",
    "Sacrificial multiplier - ": "牺牲乘数 -",
    "Loading ambient music (": "加载环境音乐（",
    "Loading music...": "加载音乐...",
    "Loading welcoming ascend music (": "加载欢迎转生音乐 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Time left until next tick \n(.+) seconds$/, '距离下一个tick还有 \n$1 秒'],
    [/^Flask contains (.+) prestige$/, '烧瓶包含 $1 声望'],
    [/^You have (.+) second$/, '你有 $1 秒'],
    [/^You have (.+) seconds$/, '你有 $1 秒'],
    [/^You have (.+) prestige points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)\% Key done$/, '$1\% 键完成'],
    [/^([\d\.]+)x multiplier$/, '$1x 乘数'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) tick tocks$/, '$1 嘀嗒'],
    [/^([\d\.,]+) prestige point$/, '$1 声望点'],
    [/^([\d\.,]+) prestige points$/, '$1 声望点'],
    [/^([\d\.,]+)k Dust$/, '$1k 灰尘'],
    [/^([\d\.,]+)k Shards$/, '$1k 碎片'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);